config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post "searches/checks", to: "searches#update_or_create", as: "update_or_create"
  resources :searches
  post "/searches/opinion", to: "searches#opinion", as: "opinion"
  get "searches/show", to: "searches#show", as: "show_search"
  post "searches/update", to: "searches#update", as: "update_search"
  # resources :series_lists
  get "/series_lists/:id", to: "series_lists#show", as: "series_list"
  get "/recommended", to: "searches#recommendations"
  root to: "series_lists#popular"
  get "home/new"
  get "home/index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/series_list.rb
require "Request"
require "ApiConnection"
class SeriesList < ApplicationRecord
  enum list_type: [
    :liked,
    :disliked,
    :search,
    :recommended
  ]
  # should have a method here to return series info for each series in external_series object
  BASE = "https://api.themoviedb.org/3/tv/"

  def get_series(id)
    api_response	= Request.get_json("https://api.themoviedb.org/3/tv/", id.to_s)
    seriesInfo	= api_response[0]
    raise Exception.new("status: " + api_response[1].to_s) if api_response[1] != 200

    api_response	= Request.get_json("https://api.themoviedb.org/3/tv/", (id.to_s + "/credits"))
    creditsInfo	= api_response[0]
    raise Exception.new("status: " + api_response[1].to_s) if api_response[1] != 200

    query_hash	= {'include_image_language': "en"}
    query_path	= "https://api.themoviedb.org/3/tv/" + id.to_s + "/images"
    api_response	= Request.get_json(query_path, query_hash)
    raise Exception.new("status: " + api_response[1].to_s) if api_response[1] != 200

    images = []
    api_response[0]["posters"].each { |x| images.append(x["file_path"]) }

    seriesInfo["images"]	= images[0, 4]
    seriesInfo["cast"]	= creditsInfo["cast"]
    seriesInfo
  end

  def get_list
    external_series
  end

  def get_genres(series, amount)
    genres_list	= series["genres"]
    str	= []
    amount	= genres_list.length <= amount ? genres_list.length : amount
    genres_list[0..amount].each do |genre|
      str.append(genre["name"])
    end
    str.join(", ")
  end

  def append(series_to_add)
    external_series.append(series_to_add)
    save
  end

  # this could be dangerous to the list because it replaces everything
  def set_series(series_to_add)
    self.external_series = series_to_add
    save
  end
end

app/controllers/series_lists_controller.rb
class SeriesListsController < ApplicationController
  before_action :set_series_list, only: [:show, :edit, :update, :destroy]

  # GET /series_lists
  # GET /series_lists.json
  def index
    @series_lists = SeriesList.all
  end

  def popular
    @series_list = SeriesList.find_by(search_id: 1)
  end

  # GET /series_lists/1
  # GET /series_lists/1.json
  def show
    @series_list
  end

  # GET /series_lists/new
  def new
    @series_list = SeriesList.new
  end

  # GET /series_lists/1/edit
  def edit
  end

  # POST /series_lists
  # POST /series_lists.json
  def create
    @series_list = SeriesList.new(series_list_params)

    respond_to do |format|
      if @series_list.save
        format.html { redirect_to @series_list, notice: "Series list was successfully created." }
        format.json { render :show, status: :created, location: @series_list }
      else
        format.html { render :new }
        format.json { render json: @series_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series_lists/1
  # PATCH/PUT /series_lists/1.json
  def update
    respond_to do |format|
      if @series_list.update(series_list_params)
        format.html { redirect_to @series_list, notice: "Series list was successfully updated." }
        format.json { render :show, status: :ok, location: @series_list }
      else
        format.html { render :edit }
        format.json { render json: @series_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series_lists/1
  # DELETE /series_lists/1.json
  def destroy
    @series_list.destroy
    respond_to do |format|
      format.html { redirect_to series_lists_url, notice: "Series list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_series_list
    @series_list = SeriesList.find_by_search_id(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def series_list_params
    # params.require(:series_list).permit(:api_id,, :name,language,origin_country)
  end
end

app/helpers/series_lists_helper.rb
module SeriesListsHelper
end

app/views/series_lists/_form.html.erb
<%= form_with(model: series_list, local: true) do |form| %>
  <% if series_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series_list.errors.count, "error") %> prohibited this series_list from being saved:</h2>

      <ul>
        <% series_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :api_id, %>
    <%= form.text_field :api_id, %>
  </div>

  <div class="field">
    <%= form.label :name,language,origin_country %>
    <%= form.text_field :name,language,origin_country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/series_lists/edit.html.erb
<h1>Editing Series List</h1>

<%= render 'form', series_list: @series_list %>

<%= link_to 'Show', @series_list %> |
<%= link_to 'Back', series_lists_path %>

app/views/series_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Series Lists</h1>

<table>
  <thead>
    <tr>
      <th>Api id,</th>
      <th>Name,language,origin country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series_lists.each do |series_list| %>
      <tr>
        <td><%= series_list.api_id, %></td>
        <td><%= series_list.name,language,origin_country %></td>
        <td><%= link_to 'Show', series_list %></td>
        <td><%= link_to 'Edit', edit_series_list_path(series_list) %></td>
        <td><%= link_to 'Destroy', series_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series List', new_series_list_path %>

app/views/series_lists/new.html.erb
<h1>New Series List</h1>

<%= render 'form', series_list: @series_list %>

<%= link_to 'Back', series_lists_path %>

app/views/series_lists/popular.html.erb
<div class = "Container">
    <div class = "content">
        <%= render "shared/tiles", locals: { series_list: @series_list }%> 
    </div>
</div>

app/views/series_lists/show.html.erb
<div class="row no-gutters" id="search">
    <%= render "shared/tiles", locals: { series_list: @series_list }%>
</div>